# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd13df77a71df802efde297b42f909bce2c0434b2a393142d3db19ffebe966f2986f1376b84f6a677b365ddb9ff03ce7105cf78f6b15866ff1a4d1832c5a0ce

test:
  secret_key_base: 1a74cb9b5efb9f7cc7ead018e9bee90db1212263cf7c319500b034641d284a3bbd7d4983c2abcad5856eea40cbf458b9657bbdf92fc639427de6243422ea9ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
